background = "#08131f"
foreground = "#d7e5ff"
border = "#2a8f9c"
border_focused = "#6deefc"
title = "#4ed0d0"
title_focused = "#7ffcff"
cursor = "#ffd166"
cursor_line_bg = "#14344d"
selection_bg = "#1b3f5c"
warning = "#f2a541"
error = "#f25f5c"
accent = "#ffd166"

[hl]
comment = "#547596"
doc_comment = "#7ac1ff"
string = "#9ad88f"
char = "#b1eb8f"
number = "#f2a541"
boolean = "#f5c96f"
keyword = "#7ffcff"
keyword_control = "#ff9f1c"
keyword_operator = "#ffd166"
type = "#7ac9ff"
type_builtin = "#4ed0d0"
function = "#ffd166"
method = "#ffcc8c"
macro = "#d29bff"
attribute = "#a0c4ff"
namespace = "#6deefc"
variable = "#d7e5ff"
parameter = "#ffd966"
property = "#4ed0d0"
constant = "#ff7676"
operator = "#c4d2df"
punctuation = "#6c93b1"
tag = "#4ed0d0"
heading = "#7ffcff"
emphasis = "#ffd166"
link = "#57c7ff"
error = "#f25f5c"
warning = "#f2a541"

[gol]
bg = "#071420"
live_new = "#a8fff7"
live = "#00f6ff"
live_old = "#00b3c0"
trail_1 = "#0a4a57"
trail_2 = "#083845"
trail_3 = "#062734"
bbox = "#1ad6d6"
hud_dim = "#3aa9b3"
hud_text = "#7ffcff"
hud_spark = "#ffd166"
