; SQL highlights (minimal, editor-grade, generic dialect)
(comment) @comment
(marginalia) @comment

(literal) @string

[
  (keyword_select)
  (keyword_from)
  (keyword_where)
  (keyword_insert)
  (keyword_update)
  (keyword_delete)
  (keyword_into)
  (keyword_values)
  (keyword_create)
  (keyword_table)
  (keyword_index)
  (keyword_view)
  (keyword_drop)
  (keyword_alter)
  (keyword_add)
  (keyword_column)
  (keyword_primary)
  (keyword_key)
  (keyword_foreign)
  (keyword_references)
  (keyword_unique)
  (keyword_not)
  (keyword_default)
  (keyword_check)
  (keyword_constraint)
  (keyword_join)
  (keyword_inner)
  (keyword_outer)
  (keyword_left)
  (keyword_right)
  (keyword_full)
  (keyword_on)
  (keyword_group)
  (keyword_order)
  (keyword_by)
  (keyword_having)
  (keyword_limit)
  (keyword_offset)
  (keyword_as)
  (keyword_and)
  (keyword_or)
  (keyword_in)
  (keyword_between)
  (keyword_like)
  (keyword_is)
  (keyword_exists)
  (keyword_union)
  (keyword_all)
  (keyword_distinct)
  (keyword_case)
  (keyword_when)
  (keyword_then)
  (keyword_else)
  (keyword_end)
] @keyword
