use crate::{mode::Mode, pane::PaneId};

#[derive(Clone, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum Action {
    Quit,
    Save,
    ConfirmQuitYes,
    ConfirmQuitNo,
    FocusNextPane,
    FocusPrevPane,
    FocusPane(PaneId),
    SwitchMode(Mode),
    ToggleMode,
    InsertChar(char),
    InsertNewline,
    InsertTab,
    Backspace,
    Delete,
    MoveUp,
    MoveDown,
    MoveLeft,
    MoveRight,
    PageUp,
    PageDown,
    Home,
    End,
    GoToTop,
    GoToBottom,
    ScrollUp,
    ScrollDown,
    ClearLogs,
    ToggleJobPause,
    VisualizerReseed,
    VisualizerApply,
    ShowHelp,
    HideHelp,
}
