use crate::{mode::Mode, pane::PaneId, search::SearchMode};
use std::path::PathBuf;

#[derive(Clone, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum Action {
    Quit,
    Save,
    SaveAndNormal,
    ConfirmQuitYes,
    ConfirmQuitNo,
    FocusNextPane,
    FocusPrevPane,
    FocusPane(PaneId),
    SwitchMode(Mode),
    ToggleMode,
    InsertChar(char),
    InsertNewline,
    InsertTab,
    Append,
    Backspace,
    Delete,
    DeleteLine,
    YankLine,
    EnterVisual,
    ExitVisual,
    YankSelection,
    DeleteSelection,
    Paste,
    PasteLineAbove,
    MoveUp,
    MoveDown,
    MoveLeft,
    MoveRight,
    PageUp,
    PageDown,
    Home,
    End,
    MoveWordEnd,
    MoveWordBack,
    GoToTop,
    GoToBottom,
    OpenLineBelow,
    OpenLineAbove,
    Undo,
    Redo,
    ScrollUp,
    ScrollDown,
    ClearLogs,
    ToggleJobPause,
    CommandPromptOpen,
    CommandPromptCancel,
    CommandPromptBackspace,
    CommandPromptMoveLeft,
    CommandPromptMoveRight,
    CommandPromptExecute,
    CommandPromptInput(char),
    VisualizerReseed,
    VisualizerApply,
    VisualizerToggleSearch,
    VisualizerToggleWrap,
    VisualizerToggleSeedSource,
    VisualizerSnapshot,
    VisualizerPause,
    VisualizerCycleAutoStop,
    VisualizerSpeedUp,
    VisualizerSpeedDown,
    VisualizerRun,
    VisualizerStop,
    GamesRun,
    GamesStop,
    GamesHide,
    GamesShow,
    GamesHistoryOpen,
    VisualizerCycleRenderMode,
    VisualizerToggleAgeShading,
    VisualizerToggleTrails,
    VisualizerToggleBBox,
    VisualizerToggleHeat,
    VisualizerToggleScanlines,
    VisualizerCycleSeedView,
    VisualizerCycleEncoder,
    VisualizerCycleSeedOverlays,
    VisualizerCycleSymmetry,
    VisualizerToggleSeedView,
    VisualizerInspectLeft,
    VisualizerInspectRight,
    VisualizerInspectUp,
    VisualizerInspectDown,
    VisualizerInspectHome,
    VisualizerInspectEnd,
    VisualizerInspectCenter,
    VisualizerInspectToggle,
    VisualizerInspectJump(u64),
    GateMonitorToggleSubView,
    VisualizerToggleSubView,
    SetGolRuleById(String),
    SetGolRuleByString(String),
    OpenRulePicker,
    OpenProtocolPicker,
    CloseModal,
    ApplySelectedRuleFromPicker,
    ApplySelectedProtocolFromPicker,
    PetriShow,
    ShowHelp,
    HideHelp,
    ToggleSyntax,
    ToggleDebug,
    ToggleFileTree,
    OpenFile(PathBuf),
    OpenSearchPopup(SearchMode),
    CloseSearchPopup,
    // --- Vim-style editor motions ---
    MoveWordForward,
    MoveBigWordForward,
    MoveBigWordBack,
    MoveBigWordEnd,
    MoveFirstNonBlank,
    MoveLastNonBlank,
    MoveParagraphUp,
    MoveParagraphDown,
    MoveViewportTop,
    MoveViewportMiddle,
    MoveViewportBottom,
    // --- Vim-style editor operators (no explicit motion pairing) ---
    DeleteToEnd,
    ChangeToEnd,
    SubstituteChar,
    SubstituteLine,
    JoinLines,
    ToggleCaseChar,
    ReplaceChar(char),
    /// Find a character on the current line.
    /// Fields: (ch, forward, till)
    ///   forward=true  → f / t
    ///   forward=false → F / T
    ///   till=true     → stop one character before the target (t / T)
    FindChar(char, bool, bool),
    // --- Vim-style scroll / viewport ---
    ScrollHalfPageDown,
    ScrollHalfPageUp,
    CenterViewportOnCursor,
    ViewportTopOnCursor,
    ViewportBottomOnCursor,
    // --- Vim-style in-editor word search: * / # / n / N ---
    /// `*`: set search term to word under cursor and jump to next match.
    SearchWordForward,
    /// `#`: set search term to word under cursor and jump to previous match.
    SearchWordBack,
    /// `n`: jump to next occurrence of the active search term.
    SearchNext,
    /// `N`: jump to previous occurrence of the active search term.
    SearchPrev,
    /// Clear the highlighted search term (vim's `:nohlsearch`).
    SearchClear,
    // --- `/` search prompt ---
    /// Open the `/` search input; the user types a term and Enter confirms.
    SearchPromptOpen,
    /// Cancel the search prompt without applying a term.
    SearchPromptCancel,
    /// Execute the search (Enter in prompt): set the term and jump to next match.
    SearchPromptExecute,
    /// Append a char into the search prompt input.
    SearchPromptInput(char),
    /// Backspace inside the search prompt.
    SearchPromptBackspace,
}
