use std::path::{Path, PathBuf};

use super::*;

pub(super) const MAX_FAMILY_RUN_MACHINES_CPU: usize = 10_000;
const MAX_FAMILY_RUN_MACHINES_METAL: usize = 100_000;
const DEFAULT_FAMILY_CA_T: u32 = 10;
// Notebook default for `TuringMachineStrategy[tm]`.
pub(super) const DEFAULT_FAMILY_TM_MAX_STEPS: u32 = 1000;
const FAMILY_RUN_CONFIG_PREFIX: &str = "# generated by :games run <family> {...}";
const MAX_FAMILY_TOTAL_MATCHES_CPU: u128 = 500_000;
const MAX_FAMILY_TOTAL_ROUND_OPS_CPU: u128 = 50_000_000;

pub fn apply_family_run_runtime_overrides(config: &mut nit_games::NormalizedConfig) {
    config.engine.mode = nit_games::EngineMode::Batch;
    config.event_log.enabled = false;
    config.history.enabled = false;
    config.engine.fast_eval = true;
}

pub(super) fn build_family_run_override(
    _state: &AppState,
    family: &str,
    input: &str,
    force: bool,
) -> Result<GamesFamilyRunRequest, String> {
    let family = family.to_ascii_lowercase();
    match family.as_str() {
        "fsm" => {
            parse_fsm_family_tuple(input)?;
        }
        "tm" => {
            parse_tm_family_request(input)?;
        }
        "ca" => {
            parse_ca_family_tuple(input)?;
        }
        _ => {
            return Err(
                "Usage: :games run [force] <fsm|ca|tm> {params} (e.g. :games run fsm {2, 2})"
                    .into(),
            )
        }
    }

    Ok(GamesFamilyRunRequest {
        family,
        input: input.to_string(),
        force,
    })
}

pub fn build_family_run_override_for_request(
    workspace_root: &std::path::Path,
    config_text: &str,
    request: &GamesFamilyRunRequest,
) -> Result<GamesRunOverride, String> {
    build_family_run_override_for_request_with_timings(workspace_root, config_text, request)
        .map(|(override_run, _)| override_run)
}

pub fn build_family_run_override_for_request_with_timings(
    workspace_root: &std::path::Path,
    config_text: &str,
    request: &GamesFamilyRunRequest,
) -> Result<(GamesRunOverride, FamilyRunBuildTimings), String> {
    let base_config = nit_games::config::GamesConfig::family_run_base_from_toml_with_root(
        config_text,
        Some(workspace_root),
    )
    .map_err(|err| format!("Config error: {err}"))?;
    build_family_run_override_from_base_config_with_timings(
        workspace_root,
        config_text,
        request,
        base_config,
    )
}

pub fn build_family_run_override_from_base_config(
    workspace_root: &std::path::Path,
    config_text: &str,
    request: &GamesFamilyRunRequest,
    base_config: nit_games::config::FamilyRunBaseConfig,
) -> Result<GamesRunOverride, String> {
    build_family_run_override_from_base_config_with_timings(
        workspace_root,
        config_text,
        request,
        base_config,
    )
    .map(|(override_run, _)| override_run)
}

pub fn build_family_run_override_from_base_config_with_timings(
    workspace_root: &std::path::Path,
    config_text: &str,
    request: &GamesFamilyRunRequest,
    base_config: nit_games::config::FamilyRunBaseConfig,
) -> Result<(GamesRunOverride, FamilyRunBuildTimings), String> {
    let build_started = Instant::now();
    let config = &base_config;
    let metal_available = config.engine.accelerator.allows_metal();

    let generation_started = Instant::now();
    let (strategies, label) = match request.family.as_str() {
        "fsm" => {
            let (states, actions) = parse_fsm_family_tuple(&request.input)?;
            let (specs, stats) = generate_fsm_family_strategies(
                workspace_root,
                states,
                actions,
                config.engine.fsm_grouping,
            )?;
            (
                specs,
                format!(
                    "fsm {{s={states}, k={actions}, grouping={}}}; raw→canonical→unique = {}→{}→{}",
                    fsm_grouping_mode_label(config.engine.fsm_grouping),
                    stats.raw_count,
                    stats.canonical_count,
                    stats.unique_behavior_count
                ),
            )
        }
        "tm" => {
            let (states, symbols, max_steps_override) = parse_tm_family_request(&request.input)?;
            let (blank, default_max_steps) = default_tm_family_params(config.tm_blank_hint);
            let max_steps = max_steps_override.unwrap_or(default_max_steps);
            let specs =
                generate_tm_family_strategies(states, symbols, blank, max_steps, metal_available)?;
            (
                specs,
                format!("tm {{s={states}, k={symbols}, max_steps={max_steps}}}"),
            )
        }
        "ca" => {
            let (symbols, two_r, t) = parse_ca_family_tuple(&request.input)?;
            let specs = generate_ca_family_strategies(symbols, two_r, t, metal_available)?;
            (
                specs,
                format!("ca {{k={symbols}, r={}, t={t}}}", two_r as f32 / 2.0),
            )
        }
        _ => {
            return Err(
                "Usage: :games run [force] <fsm|ca|tm> {params} (e.g. :games run fsm {2, 2})"
                    .into(),
            )
        }
    };
    let generation_elapsed = generation_started.elapsed();

    if strategies.is_empty() {
        return Err(format!("No strategies generated for {label}"));
    }
    let generated_strategies = strategies.len();
    let estimate_started = Instant::now();
    let total_matches =
        estimate_total_matches(strategies.len(), config.repetitions, config.self_play)?;
    let total_round_ops = total_matches.saturating_mul(config.rounds.max(1) as u128);
    let estimate_elapsed = estimate_started.elapsed();
    let metal_available = config.engine.accelerator.allows_metal();
    if !request.force && !metal_available {
        if total_matches > MAX_FAMILY_TOTAL_MATCHES_CPU {
            return Err(format!(
                "Family run too large for CPU: {total_matches} matches exceed cap {MAX_FAMILY_TOTAL_MATCHES_CPU}. Use `accelerator = \"metal\"` or force."
            ));
        }
        if total_round_ops > MAX_FAMILY_TOTAL_ROUND_OPS_CPU {
            return Err(format!(
                "Family run too large for CPU: {total_round_ops} round-ops exceeds cap {MAX_FAMILY_TOTAL_ROUND_OPS_CPU}. Use `accelerator = \"metal\"` or force."
            ));
        }
    }
    let normalize_started = Instant::now();
    let mut config = base_config.into_normalized(strategies);
    apply_family_run_runtime_overrides(&mut config);
    let normalize_elapsed = normalize_started.elapsed();
    if config.strategies.is_empty() {
        return Err(format!("No strategies generated for {label}"));
    }
    let (tm_filter, tm_filter_elapsed) = if request.family == "tm" {
        let filter_started = Instant::now();
        let (filtered, diagnostics) =
            nit_games::try_select_halting_turing_machine_strategies_with_diagnostics(config)?;
        config = filtered;
        (Some(diagnostics), Some(filter_started.elapsed()))
    } else {
        (None, None)
    };
    if config.strategies.is_empty() {
        return Err(format!("No strategies generated for {label}"));
    }
    let generated_text = format!("{FAMILY_RUN_CONFIG_PREFIX}\n# {label}\n{config_text}");
    Ok((
        GamesRunOverride {
            config,
            config_text: generated_text,
            label,
            family_mode: true,
        },
        FamilyRunBuildTimings {
            generated_strategies,
            generation_elapsed,
            estimate_elapsed,
            normalize_elapsed,
            tm_filter_elapsed,
            tm_filter,
            total_elapsed: build_started.elapsed(),
        },
    ))
}

pub(super) fn estimate_total_matches(
    strategy_count: usize,
    repetitions: u32,
    self_play: bool,
) -> Result<u128, String> {
    let count = strategy_count as u128;
    let reps = repetitions as u128;
    let per_repetition = if self_play {
        count.checked_mul(count)
    } else {
        count.checked_mul(count.saturating_sub(1))
    }
    .ok_or_else(|| "Family run match-count overflow".to_string())?;
    per_repetition
        .checked_mul(reps)
        .ok_or_else(|| "Family run match-count overflow".to_string())
}

fn parse_braced_parts<'a>(input: &'a str, usage: &str) -> Result<(Vec<&'a str>, &'a str), String> {
    let Some(start) = input.find('{') else {
        return Err(usage.to_string());
    };
    let Some(end_rel) = input[start..].find('}') else {
        return Err(format!("{usage} (missing '}}')"));
    };
    let end = start + end_rel;
    let inner = &input[start + 1..end];
    let tail = input[end + 1..].trim();
    let parts: Vec<&str> = inner
        .split(|c: char| c == ',' || c.is_whitespace())
        .filter(|part| !part.is_empty())
        .collect();
    if parts.is_empty() {
        Err(usage.to_string())
    } else {
        Ok((parts, tail))
    }
}

fn parse_fsm_family_tuple(input: &str) -> Result<(usize, usize), String> {
    let usage = "Usage: :games run fsm {states, k} (example: :games run fsm {2, 2})";
    let (parts, _) = parse_braced_parts(input, usage)?;
    if parts.len() != 2 {
        return Err("FSM family tuple must be {states, k}".into());
    }

    let mut states_raw: Option<u64> = None;
    let mut actions_raw: Option<u64> = None;

    for part in parts {
        let token = part.trim();
        if let Some((key_raw, value_raw)) = token.split_once('=') {
            let key = key_raw.trim().to_ascii_lowercase();
            let value = value_raw.trim().parse::<u64>().map_err(|_| {
                format!("FSM family tuple: '{key}' value must be an integer (example: {{2, 2}})")
            })?;
            match key.as_str() {
                "s" | "state" | "states" => states_raw = Some(value),
                "k" | "actions" => actions_raw = Some(value),
                _ => return Err(
                    "FSM family tuple: unknown key; use 's'/'states' and 'k' (example: {s=2, k=2})"
                        .into(),
                ),
            }
            continue;
        }

        if token.eq_ignore_ascii_case("s")
            || token.eq_ignore_ascii_case("state")
            || token.eq_ignore_ascii_case("states")
            || token.eq_ignore_ascii_case("k")
        {
            return Err(
                "FSM family tuple placeholders need numeric values (example: :games run fsm {2, 2})"
                    .into(),
            );
        }

        let value = token.parse::<u64>().map_err(|_| {
            "FSM family tuple entries must be integers (example: :games run fsm {2, 2})".to_string()
        })?;
        if states_raw.is_none() {
            states_raw = Some(value);
        } else if actions_raw.is_none() {
            actions_raw = Some(value);
        } else {
            return Err("FSM family tuple must be {states, k}".into());
        }
    }

    let states_raw = states_raw
        .ok_or_else(|| "FSM family tuple missing states value (example: {2, 2})".to_string())?;
    let actions_raw = actions_raw
        .ok_or_else(|| "FSM family tuple missing k value (example: {2, 2})".to_string())?;

    if states_raw == 0 || states_raw > usize::MAX as u64 {
        return Err(format!(
            "FSM family tuple: states must be in 1..={}",
            usize::MAX
        ));
    }
    if actions_raw != 2 {
        return Err("FSM family tuple currently requires k=2".into());
    }
    Ok((states_raw as usize, actions_raw as usize))
}

fn parse_tm_family_request(input: &str) -> Result<(u16, u8, Option<u32>), String> {
    let usage = "Usage: :games run tm {states, symbols} [max_steps]";
    let (parts, tail) = parse_braced_parts(input, usage)?;
    if parts.len() != 2 {
        return Err("TM family tuple must be {states, symbols}".into());
    }
    let states_raw = parts[0]
        .parse::<u64>()
        .map_err(|_| "TM family tuple: states must be an integer".to_string())?;
    let symbols_raw = parts[1]
        .parse::<u64>()
        .map_err(|_| "TM family tuple: symbols must be an integer".to_string())?;
    if states_raw == 0 || states_raw > u16::MAX as u64 {
        return Err(format!(
            "TM family tuple: states must be in 1..={}",
            u16::MAX
        ));
    }
    if symbols_raw < 2 || symbols_raw > u8::MAX as u64 {
        return Err(format!(
            "TM family tuple: symbols must be in 2..={}",
            u8::MAX
        ));
    }
    let max_steps = if tail.is_empty() {
        None
    } else {
        let Some(token) = tail.split_whitespace().next() else {
            return Err(usage.into());
        };
        if tail.split_whitespace().count() != 1 {
            return Err("TM family max_steps must be a single integer after the tuple".into());
        }
        let value_token = if let Some((key, value)) = token.split_once('=') {
            match key.trim().to_ascii_lowercase().as_str() {
                "steps" | "max_steps" | "max_steps_per_round" => value.trim(),
                _ => {
                    return Err(
                        "TM family max_steps key must be `steps`, `max_steps`, or `max_steps_per_round`"
                            .into(),
                    )
                }
            }
        } else {
            token
        };
        let steps_raw = value_token
            .parse::<u64>()
            .map_err(|_| "TM family max_steps must be an integer".to_string())?;
        if steps_raw == 0 || steps_raw > u32::MAX as u64 {
            return Err(format!("TM family max_steps must be in 1..={}", u32::MAX));
        }
        Some(steps_raw as u32)
    };
    Ok((states_raw as u16, symbols_raw as u8, max_steps))
}

fn parse_ca_family_tuple(input: &str) -> Result<(u8, u32, u32), String> {
    let usage = "Usage: :games run ca {k, r} (or {k, r, t})";
    let (parts, _) = parse_braced_parts(input, usage)?;
    if parts.len() != 2 && parts.len() != 3 {
        return Err("CA family tuple must be {k, r} or {k, r, t}".into());
    }
    let symbols_raw = parts[0]
        .parse::<u64>()
        .map_err(|_| "CA family tuple: k must be an integer".to_string())?;
    if symbols_raw < 2 || symbols_raw > u8::MAX as u64 {
        return Err(format!("CA family tuple: k must be in 2..={}", u8::MAX));
    }
    let two_r = parse_two_r_token(parts[1])
        .ok_or_else(|| "CA family tuple: r must satisfy r >= 0 and IntegerQ[2r]".to_string())?;
    let t = if parts.len() == 3 {
        let t_raw = parts[2]
            .parse::<u64>()
            .map_err(|_| "CA family tuple: t must be an integer".to_string())?;
        if t_raw == 0 || t_raw > u32::MAX as u64 {
            return Err(format!("CA family tuple: t must be in 1..={}", u32::MAX));
        }
        t_raw as u32
    } else {
        DEFAULT_FAMILY_CA_T
    };
    Ok((symbols_raw as u8, two_r, t))
}

fn checked_machine_count(
    count: u128,
    family: &str,
    metal_available: bool,
) -> Result<usize, String> {
    if count == 0 {
        return Err(format!("{family} family has zero machines"));
    }
    let limit = if metal_available {
        MAX_FAMILY_RUN_MACHINES_METAL
    } else {
        MAX_FAMILY_RUN_MACHINES_CPU
    };
    if count > limit as u128 {
        return Err(format!(
            "{family} family run would generate {count} machines; limit is {limit}{}",
            if !metal_available {
                ". Use `accelerator = \"metal\"` to raise the limit"
            } else {
                ""
            }
        ));
    }
    usize::try_from(count).map_err(|_| format!("{family} family machine count does not fit usize"))
}

fn checked_pow_u128_exp(mut base: u128, mut exp: u128) -> Option<u128> {
    let mut out = 1u128;
    while exp > 0 {
        if exp & 1 == 1 {
            out = out.checked_mul(base)?;
        }
        exp >>= 1;
        if exp > 0 {
            base = base.checked_mul(base)?;
        }
    }
    Some(out)
}

struct FsmFamilyStats {
    raw_count: u128,
    canonical_count: usize,
    unique_behavior_count: usize,
}

pub(super) const FSM_FAMILY_CACHE_SCHEMA_VERSION: u32 = 1;

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub(super) struct FsmFamilyCacheEntry {
    pub(super) schema_version: u32,
    pub(super) states: usize,
    pub(super) actions: usize,
    pub(super) grouping_mode: nit_games::FsmGroupingMode,
    pub(super) canonical_count: usize,
    pub(super) representative_indices: Vec<u64>,
}

fn fsm_grouping_mode_label(mode: nit_games::FsmGroupingMode) -> &'static str {
    match mode {
        nit_games::FsmGroupingMode::Wnbm => "wnbm",
        nit_games::FsmGroupingMode::Moorem => "moorem",
    }
}

fn fsm_family_cache_dir(workspace_root: &Path) -> PathBuf {
    workspace_root
        .join(".nit")
        .join("cache")
        .join("games")
        .join("fsm")
}

pub(super) fn fsm_family_cache_path(
    workspace_root: &Path,
    states: usize,
    actions: usize,
    grouping_mode: nit_games::FsmGroupingMode,
) -> PathBuf {
    fsm_family_cache_dir(workspace_root).join(format!(
        "s{states}_k{actions}_{}_v{FSM_FAMILY_CACHE_SCHEMA_VERSION}.json",
        fsm_grouping_mode_label(grouping_mode)
    ))
}

fn load_fsm_family_cache_entry(
    workspace_root: &Path,
    states: usize,
    actions: usize,
    grouping_mode: nit_games::FsmGroupingMode,
) -> Option<FsmFamilyCacheEntry> {
    let path = fsm_family_cache_path(workspace_root, states, actions, grouping_mode);
    let contents = fs::read(path).ok()?;
    let entry: FsmFamilyCacheEntry = serde_json::from_slice(&contents).ok()?;
    if entry.schema_version != FSM_FAMILY_CACHE_SCHEMA_VERSION
        || entry.states != states
        || entry.actions != actions
        || entry.grouping_mode != grouping_mode
    {
        return None;
    }
    Some(entry)
}

fn persist_fsm_family_cache_entry(workspace_root: &Path, entry: &FsmFamilyCacheEntry) {
    let path = fsm_family_cache_path(
        workspace_root,
        entry.states,
        entry.actions,
        entry.grouping_mode,
    );
    let Some(parent) = path.parent() else {
        return;
    };
    if fs::create_dir_all(parent).is_err() {
        return;
    }
    let Ok(encoded) = serde_json::to_vec(entry) else {
        return;
    };
    let _ = fs::write(path, encoded);
}

fn generate_fsm_family_strategies(
    workspace_root: &Path,
    states: usize,
    actions: usize,
    grouping_mode: nit_games::FsmGroupingMode,
) -> Result<(Vec<nit_games::StrategySpec>, FsmFamilyStats), String> {
    let total_count = nit_games::fsm_count(states, actions)
        .ok_or_else(|| "FSM family count overflow".to_string())?;
    let cache_entry = load_fsm_family_cache_entry(workspace_root, states, actions, grouping_mode);
    let (representative_indices, canonical_count) = if let Some(entry) = cache_entry {
        (entry.representative_indices, entry.canonical_count)
    } else {
        let representative_indices = nit_games::unique_fsm_behavior_representatives_with_mode(
            states,
            actions,
            grouping_mode,
        )?;
        let canonical_count = nit_games::canonical_fsm_indices(states, actions)?.len();
        persist_fsm_family_cache_entry(
            workspace_root,
            &FsmFamilyCacheEntry {
                schema_version: FSM_FAMILY_CACHE_SCHEMA_VERSION,
                states,
                actions,
                grouping_mode,
                canonical_count,
                representative_indices: representative_indices.clone(),
            },
        );
        (representative_indices, canonical_count)
    };
    let unique_behavior_count = representative_indices.len();
    let mut specs = Vec::with_capacity(unique_behavior_count);
    for rule_index in representative_indices {
        let (outputs, transitions) =
            nit_games::decode_fsm_notebook_index(rule_index, states, actions)
                .map_err(|err| format!("FSM index decode error for {rule_index}: {err}"))?;
        specs.push(nit_games::StrategySpec {
            id: format!("fsm_{rule_index}"),
            name: None,
            kind: nit_games::config::StrategySpecKind::Fsm {
                num_states: states,
                start_state: 0,
                outputs,
                input_mode: Some(nit_games::InputMode::OpponentLastAction),
                transitions,
                index: Some(rule_index),
            },
        });
    }
    Ok((
        specs,
        FsmFamilyStats {
            raw_count: total_count,
            canonical_count,
            unique_behavior_count,
        },
    ))
}

fn default_tm_family_params(blank_hint: Option<u8>) -> (u8, u32) {
    // For compatibility with Results-06 / Code-02 notebook defaults, prefer the
    // notebook's TM max-step default rather than inheriting from the current config.
    let blank = blank_hint.unwrap_or(0);
    (blank, DEFAULT_FAMILY_TM_MAX_STEPS)
}

fn generate_tm_family_strategies(
    states: u16,
    symbols: u8,
    blank: u8,
    max_steps: u32,
    metal_available: bool,
) -> Result<Vec<nit_games::StrategySpec>, String> {
    if blank >= symbols {
        return Err(format!(
            "TM family tuple: blank symbol {blank} out of range for symbols={symbols}"
        ));
    }
    let max_index = nit_games::tm_max_index(states as usize, symbols as usize)
        .ok_or_else(|| "TM family index space overflow".to_string())?;
    let count = max_index
        .checked_add(1)
        .ok_or_else(|| "TM family index space overflow".to_string())?;
    let machine_count = checked_machine_count(count, "TM", metal_available)?;
    let mut specs = Vec::with_capacity(machine_count);
    let output_map: Vec<nit_games::Action> = (0..symbols)
        .map(|symbol| {
            if symbol == 0 {
                nit_games::Action::Cooperate
            } else {
                nit_games::Action::Defect
            }
        })
        .collect();
    for index in 0..machine_count {
        let rule_code = index as u64;
        let (transitions, _remaining) =
            nit_games::decode_tm_rule_code_wolfram(rule_code, states as usize, symbols as usize);
        specs.push(nit_games::StrategySpec {
            id: format!("tm_{rule_code}"),
            name: None,
            kind: nit_games::config::StrategySpecKind::OneSidedTm {
                states,
                symbols,
                start_state: 1,
                blank,
                fallback_symbol: Some(blank),
                max_steps_per_round: max_steps,
                input_mode: nit_games::InputMode::OpponentLastAction,
                output_map: output_map.clone(),
                transitions,
                rule_code: Some(rule_code),
            },
        });
    }
    Ok(specs)
}

fn generate_ca_family_strategies(
    symbols: u8,
    two_r: u32,
    t: u32,
    metal_available: bool,
) -> Result<Vec<nit_games::StrategySpec>, String> {
    let neighborhood = two_r.saturating_add(1) as u128;
    let table_len = checked_pow_u128_exp(symbols as u128, neighborhood)
        .ok_or_else(|| "CA family rule-table size overflow".to_string())?;
    let rule_count = checked_pow_u128_exp(symbols as u128, table_len)
        .ok_or_else(|| "CA family rule count overflow".to_string())?;
    let machine_count = checked_machine_count(rule_count, "CA", metal_available)?;
    let mut specs = Vec::with_capacity(machine_count);
    for index in 0..machine_count {
        let n = index as u64;
        specs.push(nit_games::StrategySpec {
            id: format!("ca_{n}"),
            name: None,
            kind: nit_games::config::StrategySpecKind::Ca {
                n,
                k: symbols,
                r: two_r as f32 / 2.0,
                t,
            },
        });
    }
    Ok(specs)
}

pub(super) fn parse_ca_rule_tuple(input: &str) -> Result<Option<(u64, u8, u32, u32)>, String> {
    const DEFAULT_CA_T: u32 = 10;
    let Some(start) = input.find('{') else {
        return Ok(None);
    };
    let Some(end_rel) = input[start..].find('}') else {
        return Err("CA rule tuple missing '}'".into());
    };
    let end = start + end_rel;
    let inner = &input[start + 1..end];
    let parts: Vec<&str> = inner
        .split(|c: char| c == ',' || c.is_whitespace())
        .filter(|part| !part.is_empty())
        .collect();
    if parts.len() != 3 && parts.len() != 4 {
        return Err("CA rule tuple must be {n, k, r} (or {n, k, r, t})".into());
    }
    let n = parts[0]
        .parse::<u64>()
        .map_err(|_| "CA rule tuple: n must be an integer".to_string())?;
    let k_raw = parts[1]
        .parse::<u64>()
        .map_err(|_| "CA rule tuple: k must be an integer".to_string())?;
    if k_raw < 2 || k_raw > u8::MAX as u64 {
        return Err(format!("CA rule tuple: k must be in 2..={}", u8::MAX));
    }
    let two_r = parse_two_r_token(parts[2])
        .ok_or_else(|| "CA rule tuple: r must satisfy r >= 0 and IntegerQ[2r]".to_string())?;
    let t = if parts.len() == 4 {
        let t_raw = parts[3]
            .parse::<u64>()
            .map_err(|_| "CA rule tuple: t must be an integer".to_string())?;
        if t_raw == 0 || t_raw > u32::MAX as u64 {
            return Err(format!("CA rule tuple: t must be in 1..={}", u32::MAX));
        }
        t_raw as u32
    } else {
        DEFAULT_CA_T
    };
    Ok(Some((n, k_raw as u8, two_r, t)))
}

fn parse_two_r_token(token: &str) -> Option<u32> {
    let token = token.trim();
    if token.is_empty() {
        return None;
    }
    if let Some((numer, denom)) = token.split_once('/') {
        let numer = numer.trim().parse::<i64>().ok()?;
        let denom = denom.trim().parse::<i64>().ok()?;
        if denom == 0 || numer < 0 {
            return None;
        }
        let two_numer = numer.checked_mul(2)?;
        if two_numer % denom != 0 {
            return None;
        }
        let two_r = two_numer / denom;
        if two_r < 0 || two_r > u32::MAX as i64 {
            return None;
        }
        return Some(two_r as u32);
    }

    let value = token.parse::<f64>().ok()?;
    if !value.is_finite() || value < 0.0 {
        return None;
    }
    let doubled = value * 2.0;
    let rounded = doubled.round();
    if (doubled - rounded).abs() > 1e-6 {
        return None;
    }
    if rounded < 0.0 || rounded > u32::MAX as f64 {
        return None;
    }
    Some(rounded as u32)
}

pub(super) fn parse_tm_rule_tuple(input: &str) -> Result<Option<(u64, u16, u8)>, String> {
    let Some(start) = input.find('{') else {
        return Ok(None);
    };
    let Some(end_rel) = input[start..].find('}') else {
        return Err("TM rule tuple missing '}'".into());
    };
    let end = start + end_rel;
    let inner = &input[start + 1..end];
    let parts: Vec<&str> = inner
        .split(|c: char| c == ',' || c.is_whitespace())
        .filter(|part| !part.is_empty())
        .collect();
    if parts.len() != 3 {
        return Err("TM rule tuple must be {rule_code, states, symbols}".into());
    }
    let rule_code = parts[0]
        .parse::<u64>()
        .map_err(|_| "TM rule tuple: rule_code must be an integer".to_string())?;
    let states_raw = parts[1]
        .parse::<u64>()
        .map_err(|_| "TM rule tuple: states must be an integer".to_string())?;
    let symbols_raw = parts[2]
        .parse::<u64>()
        .map_err(|_| "TM rule tuple: symbols must be an integer".to_string())?;
    if states_raw == 0 || states_raw > u16::MAX as u64 {
        return Err(format!("TM rule tuple: states must be in 1..={}", u16::MAX));
    }
    if symbols_raw == 0 || symbols_raw > u8::MAX as u64 {
        return Err(format!("TM rule tuple: symbols must be in 1..={}", u8::MAX));
    }
    Ok(Some((rule_code, states_raw as u16, symbols_raw as u8)))
}

pub(super) fn parse_tm_input_token(token: &str) -> Option<u64> {
    if let Ok(value) = token.parse::<u64>() {
        return Some(value);
    }
    let (base_str, exp_str) = token.split_once('^')?;
    if base_str.is_empty() || exp_str.is_empty() {
        return None;
    }
    let base = base_str.parse::<u64>().ok()?;
    let exp = exp_str.parse::<u32>().ok()?;
    if base < 2 {
        return None;
    }
    base.checked_pow(exp)
}
