name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        toolchain: [1.88.0, stable]
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: Install tools
        if: matrix.toolchain == '1.88.0'
        run: |
          cargo install cargo-deny --locked --version 0.14.24
      - name: Fmt
        if: matrix.toolchain == '1.88.0'
        run: cargo fmt --all -- --check
      - name: Clippy
        if: matrix.toolchain == '1.88.0'
        run: cargo clippy --locked --all-targets --all-features -- -D warnings
      - name: Test
        run: cargo test --all --locked --no-fail-fast
      - name: Cargo deny
        if: matrix.toolchain == '1.88.0'
        run: cargo deny check
